services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        tty: true
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: postgres
            DB_PORT: 5432
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: passw@rd
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:80"
    postgres:
        image: postgres:14.7-alpine3.17
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: passw@rd
            POSTGRES_DB: laravel
        ports:
            - "5432:5432"
        volumes:
            - postgresql:/var/lib/postgresql/data
    phppgadmin:
        image: bitnami/phppgadmin:latest
        environment:
            DATABASE_ENABLE_EXTRA_LOGIN_SECURITY: yes
            PHPPGADMIN_ALLOW_REMOTE_CONNECTIONS: yes
            PHP_PG_ADMIN_SERVER_SSL_MODE: disable
            APACHE_HTTP_PORT_NUMBER: 8181
            DATABASE_HOST: postgres
        depends_on:
            - postgres
        ports:
            - "8181:8181"
volumes:
    postgresql:
